name: Testes Automatizados

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código-fonte
        uses: actions/checkout@v2

      - name: Configuração do ambiente Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Instalação das dependências do projeto
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execução dos testes com Robot Framework
        run: |
           robot -d logs tests

      - name: Upload dos resultados dos testes
        uses: actions/upload-artifact@v2
        with:
          name: Test Results
          path: results/
